package io.open.elements.event;

public enum OPENEVENTFLAG {
PROCESS_RELATIONAL_DATA,
VALIDATE_COMPONENT_BY_NAME,
INCREMENT_VERSION_ID,
CHECK_PARENT_COMPONENT_BY_NAME,
CHECK_COMPONENT_BY_NAMETYPE,
PROCESS_ITEM,
ISDIRTY,
GET_COMOPSITER_ELEMENT,GET_REL_ON_COMPOSITERID_TYPE,GET_UNIQUE_ON_SCAN_1,
ON_OPEN,
LC_REG,
LC_CONFIG_INIT,
LC_RC_FETCH
}
